# Generated by Django 5.0 on 2024-11-21 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop_down',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('icon', models.CharField(default='none', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('role', models.CharField(default='none', max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(default='images/shinchan.webp', upload_to='images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('icon', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='caampus_care_app.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=50)),
                ('room_number', models.IntegerField()),
                ('Department', models.CharField(max_length=50)),
                ('role', models.CharField(default='S', max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=80)),
                ('image', models.ImageField(default='images/shinchan.webp', upload_to='images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
