# Generated by Django 5.0 on 2024-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0003_navbar_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
