# Generated by Django 5.0 on 2024-11-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0004_navbar_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop_down',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='drop_down',
            name='type',
        ),
        migrations.AddField(
            model_name='drop_down',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='caampus_care_app.drop_down'),
        ),
    ]
