# Generated by Django 5.0 on 2024-11-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0006_alter_drop_down_parent_alter_faculty_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
