# Generated by Django 5.0 on 2024-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0007_remove_faculty_role_remove_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
