# Generated by Django 5.0 on 2024-11-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0008_user_role_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
