# Generated by Django 5.0 on 2024-11-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0009_user_role_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='id_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.drop_down'),
        ),
    ]
