# Generated by Django 5.0 on 2024-11-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0010_navbar_id_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='role',
        ),
    ]
