# Generated by Django 5.0 on 2024-11-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0011_remove_navbar_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='id_role',
            new_name='role',
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.drop_down')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_warden', models.IntegerField(default=0)),
                ('res_rector', models.IntegerField(default=0)),
                ('res_chiefRector', models.IntegerField(default=0)),
                ('res_dean', models.IntegerField(default=0)),
                ('confirm_student', models.IntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.grievance')),
            ],
        ),
    ]
