# Generated by Django 5.0 on 2024-11-28 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0012_rename_id_role_navbar_role_grievance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='dept',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='grievance',
            old_name='is_solved',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='reason',
        ),
        migrations.AddField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grievance',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='images',
            field=models.ImageField(default=None, upload_to='grievance_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Grievance_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=0)),
                ('grievance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.grievance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Grievance_status',
        ),
    ]
