# Generated by Django 5.0 on 2024-12-01 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0013_rename_dept_grievance_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
