# Generated by Django 5.0 on 2024-12-01 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0014_user_role_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_role',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
