# Generated by Django 5.0 on 2024-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0015_alter_user_role_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance_manage',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
