# Generated by Django 5.0 on 2024-12-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0016_grievance_manage_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance_manage',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.drop_down'),
        ),
    ]
