# Generated by Django 5.0 on 2024-12-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0017_grievance_manage_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance_manage',
            name='role',
        ),
        migrations.RemoveField(
            model_name='grievance_manage',
            name='user',
        ),
        migrations.AddField(
            model_name='grievance_manage',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.user_role'),
        ),
    ]
