# Generated by Django 5.0 on 2024-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0018_remove_grievance_manage_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance_manage',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
