# Generated by Django 5.0 on 2024-12-02 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0019_alter_grievance_manage_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance_manage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
