# Generated by Django 5.0 on 2024-12-03 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0021_faculty_is_deleted_student_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageGreivance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_closed', models.BooleanField(default=0)),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                ('grievance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.grievance')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.drop_down')),
                ('user_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.user_role')),
            ],
        ),
    ]
