# Generated by Django 5.0 on 2024-12-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0022_managegreivance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManageGreivance',
            new_name='ManageGrievance',
        ),
        migrations.DeleteModel(
            name='Grievance_manage',
        ),
    ]
