# Generated by Django 5.0 on 2024-12-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0023_rename_managegreivance_managegrievance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToBeShown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to+', to='caampus_care_app.user_role')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caampus_care_app.drop_down')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from+', to='caampus_care_app.user_role')),
            ],
        ),
    ]
