# Generated by Django 5.0 on 2024-12-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0025_grievanceadded_alter_managegrievance_grievance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drop_down',
            new_name='Dropdown',
        ),
    ]
