# Generated by Django 5.0 on 2024-12-05 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0026_rename_drop_down_dropdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_role',
            new_name='UserRole',
        ),
    ]
