# Generated by Django 5.0 on 2024-12-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0027_rename_user_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrole',
            name='ToBeShown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to+', to='caampus_care_app.dropdown'),
        ),
        migrations.AlterField(
            model_name='actionrole',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action+', to='caampus_care_app.dropdown'),
        ),
        migrations.AlterField(
            model_name='actionrole',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from+', to='caampus_care_app.dropdown'),
        ),
    ]
