# Generated by Django 5.0 on 2024-12-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0028_alter_actionrole_tobeshown_alter_actionrole_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_deleted',
        ),

    ]
