# Generated by Django 5.0 on 2024-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0029_remove_faculty_is_deleted_remove_student_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='actionrole',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='actionrole',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        #  ),
        # migrations.AddField(
        #     model_name='student',
        #     name='ID',
        #     field=models.IntegerField(default=None, primary_key=True, serialize=False),
        #     preserve_default=False,
        # ),
    ]
