# Generated by Django 5.0 on 2024-12-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0033_remove_student_id_actionrole_created_at_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='navbar',
            name='is_child',
            field=models.BooleanField(default=False),
        )
    ]
