# Generated by Django 5.0 on 2024-11-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='caampus_care_app.navbar'),
        ),
    ]
