# Generated by Django 5.0 on 2024-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caampus_care_app', '0002_alter_navbar_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='role',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
